---
title: "render-qc-report"
output: html_document
---

```{r data-needed, include=FALSE}
library(MassExpression)

# design <- mq_lfq_data$design
# intensities <- mq_lfq_data$intensities

design <- read.table("../../data/sample-data-app/generic-importer-input/experiment_design.tsv",sep = "\t", header = TRUE)
intensities <- read.table("../../data/sample-data-app/generic-importer-input/protein_intensities.tsv",sep = "\t", header = TRUE)
# This will have to be passed with parameters files
parameters <- read.table('../../data/sample-data-app/generic-importer-input/parameters.tsv', header=FALSE, sep='\t')
normalisation_method <- parameters[parameters[,1] == "UseNormalisationMethod",2]


species <- parameters[parameters[,1] == "Species",2]
labellingMethod <- parameters[parameters[,1] == "LabellingMethod",2]


listIntensityExperiments <- runGenericDiscovery(experimentDesign = design, 
                                                proteinIntensities = intensities, 
                                                normalisationMethod = normalisation_method,
                                                species = species, 
                                                labellingMethod = labellingMethod)


# Save output to folder
Intensity <- listIntensityExperiments$IntensityExperiment
CompleteIntensity <-  listIntensityExperiments$CompleteIntensityExperiment
saveOutput(Intensity, CompleteIntensity, output_folder)


output_folder <- "~/Desktop/universal-import/"
output_folder_pdf <- file.path(output_folder, "pdf")
dir.create(output_folder_pdf)

# Render and save QC report
qc_report <- system.file("rmd","QC_report.Rmd", package = "MassExpression")
rmarkdown::render(qc_report,
                  params = list(listInt = listIntensityExperiments,
                                experiment = "Mass Dynamics QC report",
                                output_figure = file.path(output_folder, "figure_html/"),
                                format = "html"),
                  output_file = file.path(output_folder, "QC_Report.html"),
                  output_format=rmarkdown::html_document(
                            self_contained=FALSE,
                            lib_dir=file.path(output_folder,"qc_report_files"),
                            code_folding= "hide",
                            theme="united",
                            toc = TRUE,
                            toc_float = TRUE,
                            fig_caption= TRUE,
                            df_print="paged"))
# Render PDF
rmarkdown::render(qc_report,
                  params = list(listInt = listIntensityExperiments,
                                experiment = "Mass Dynamics QC report",
                                output_figure = file.path(output_folder_pdf, "figure_pdf/"),
                                format = "pdf"),
                  output_file = file.path(output_folder_pdf, "QC_Report.pdf"),
                  output_format=rmarkdown::pdf_document(
                    toc = TRUE,
                    fig_caption= TRUE))

```


## DIA-NN data

```{r}
load("../data-private/example_diann_sheep.rda")
design <- diann_sheep_data$design
intensities <- diann_sheep_data$intensities

listIntensityExperiments <- runGenericDiscovery(experimentDesign = design, 
                                                proteinIntensities = intensities, 
                                                output_folder = "~/Desktop/test")

CompleteIntensityExperiment <- listIntensityExperiments$CompleteIntensityExperiment
IntensityExperiment <- listIntensityExperiments$IntensityExperiment


rmarkdown::render('QCreport.Rmd', params = list(listInt = listIntensityExperiments, 
                                                        experiment= "DIA-NN Sheep Plasma"),
                  output_file = "DIA-NN-Sheep")
```


## Proteome Discoverer

```{r}
design <- pd_iPRG_data$design
intensities <- pd_iPRG_data$intensities

listIntensityExperiments <- runGenericDiscovery(experimentDesign = design,
                                                proteinIntensities = intensities)

CompleteIntensityExperiment <- listIntensityExperiments$CompleteIntensityExperiment
IntensityExperiment <- listIntensityExperiments$IntensityExperiment


rmarkdown::render('QCreport.Rmd', params = list(listInt = listIntensityExperiments, 
                                                        experiment= "PD LFQ"),
                  output_file = "Proteome Discoverer")
```


## Fragpipe

```{r}
design <- fragpipe_data$design
intensities <- fragpipe_data$intensities

listIntensityExperiments <- runGenericDiscovery(experimentDesign = design, proteinIntensities = intensities)

CompleteIntensityExperiment <- listIntensityExperiments$CompleteIntensityExperiment
IntensityExperiment <- listIntensityExperiments$IntensityExperiment


rmarkdown::render('QCreport.Rmd', params = list(listInt = listIntensityExperiments, 
                                                        experiment= "Fragpipe LFQ"),
                  output_file = "Fragpipe")
```
