---
title: "MassExpression"
author: "Mass Dynamics"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_caption: yes
    toc_float: true
vignette: >
  %\VignetteIndexEntry{MassExpression}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      collapse = TRUE,
                      comment = "#>")
```

```{r}
library(MassExpression)
```


# Run example end-to-end

```{r fragpipe}
outputFolder <- "output"
design <- fragpipe_data$design
intensities <- fragpipe_data$intensities

IntensityExperiment <- runGenericDiscovery(experimentDesign = design, proteinIntensities = intensities)

debugonce(runGenericDiscovery(experimentDesign = design, proteinIntensities = intensities))

writeProteinViz(outputFolder = outputFolder, IntensityExperiment=IntensityExperiment)
```

## Create output artefacts

```{r}
# Get Binary Statistic Comparisons and Long for Protein Intensity
results <- run_binary_limma_pipeline(protein.summarized.experiment)
protein.summarized.experiment <- results[[1]]
prot.int <- results[[2]]

# Construct Single Object with Update data
complete.protein.summarized.experiment <-
  get_complete_protein_summarized_experiment(protein.summarized.experiment,
                                             prot.int)

# Write Discovery Outputs
write_protein_viz(output_folder, protein.summarized.experiment)
```


```{r mq-lfq, eval=FALSE}
outputFolder <- "output"
design <- mq_lfq_data$design
intensities <- mq_lfq_data$intensities

# Something wrong with the creation of the input
IntensityExperiment <- runGenericDiscovery(experimentDesign = design, proteinIntensities = intensities)

writeProteinViz(outputFolder = outputFolder, IntensityExperiment=IntensityExperiment)
```