---
title: ""
output:
  html_document:
    theme: united
    toc: no
    fig_caption: yes
    lib_dir: qc_report_files
params:
  listInt: empty
  format: pdf
  output_figure: figures
---

```{r setup, include=FALSE}
print(params)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, 
                      fig.path = params$output_figure, dev = "svg")
```


```{r data-needed, include=FALSE, eval=TRUE}
library(dplyr)
library(stringr)
library(MassExpression)
library(plotly)

CompleteIntensityExperiment <- params$listInt$CompleteIntensityExperiment
IntensityExperiment <- params$listInt$IntensityExperiment
design <- colData(IntensityExperiment)

comparisonExperiments <- 
    listComparisonExperiments(CompleteIntensityExperiment)
```


```{r summary-de, eval=TRUE, warning=FALSE, echo=FALSE, error=FALSE, message=FALSE, results='asis'}
stats_one_comp <- function(se){
  stats <- as_tibble(rowData(se))
  
  total_proteins_in_experiment <- nrow(stats)
  total_proteins_de <- sum(stats$ADJ.PVAL < 0.05)
  list(total_proteins_in_experiment=total_proteins_in_experiment, total_proteins_de=total_proteins_de)
}

n_proteins <- sapply(1:length(comparisonExperiments), function(exp) stats_one_comp(comparisonExperiments[[exp]]))
names_experiments <- names(comparisonExperiments)
colnames(n_proteins) <- names_experiments
n_proteins <- data.frame(t(n_proteins))
n_proteins$Comparison <- rownames(n_proteins)
rownames(n_proteins) <- NULL
n_proteins <- n_proteins %>% rename(`Number of Proteins` = total_proteins_in_experiment, 
                                    `Number DE Proteins` = total_proteins_de) %>%
  select(Comparison, `Number of Proteins`, `Number DE Proteins`)

#knitr::kable(n_proteins, row.names = FALSE, caption="Summary of differential expression results across comparisons.") 

knitr::kable(n_proteins, row.names = FALSE)

# kbl() %>%
# kable_styling(full_width = F, position = "left")

```
