---
title: ""
output:
  html_document:
    theme: united
    toc: no
    fig_caption: yes
    lib_dir: qc_report_files
params:
  listInt: empty
  output_figure: figures
---

```{r setup, include=FALSE}
print(params)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, 
                      fig.path = params$output_figure, dev = "svg")
```


```{r data-needed, include=FALSE, eval=TRUE}
library(dplyr)
library(stringr)
library(MassExpression)
library(plotly)

CompleteIntensityExperiment <- params$listInt$CompleteIntensityExperiment
IntensityExperiment <- params$listInt$IntensityExperiment
design <- colData(IntensityExperiment)

comparisonExperiments <- 
    listComparisonExperiments(CompleteIntensityExperiment)
```




```{r raw-boxplots}
normalised <- FALSE
if(metadata(CompleteIntensityExperiment)$NormalisationAppliedToAssay != "None"){
  normalised <- TRUE
}

# Plot RLE of log2 raw intensity as well as RLE of normalised 
p_raw <- plot_log_measurement_boxplot(IntensityExperiment)
p_raw
```
